dist: xenial
sudo: required

language: node_js
node_js:
  - '10'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

install:
  - npm ci

script:
  - npm run lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run e2e
# - cypress run --record --key e82f2ecd-4c62-4334-b045-edfbea51acad
# This command should be in a npm script that simultaneously runs ng serve and cypress
# https://docs.cypress.io/guides/guides/continuous-integration.html#Boot-your-server


before_deploy:
  - npm run build -- --prod --no-progress
  - cd functions && npm ci && cd ..

deploy:
  - provider: firebase
    project: "default"
    skip_cleanup: true
    token:
      secure: XuQO4j7xk2YJWtkXsQtIU71CXc2LjbCB3lblmsCcYlzbIWiWk1u26YxGvifpuuQ37PT2FLFnGMsWBP41kieHEw4h/AC2VkLk0cC4vhEhoMATnDDH+4RpmpdOMxMA/lWPwuNTnYMSJm2yJWV8Nz8NjdTHDSAozV2/ZXgiDKgqosXSabpoVHTH7lTcfXJAswfgdAvkeG/k4BGm1LSHTEvU+TdA9QwjmUG9PWQkkRMkEcOuH41BvY0TNMtxsAcTy0ofoDHAkhF/uOHI1J7FaEiLS1R8DwOSBY45EKEaA3dJgBqL0genpqrN7gSF8GFetF0BRXWg9mwDDdF04pgC5C1jWmtsVIjACsLQ6AChrLtpddjwwByX14i835UlFAfCP2hGGCZ5BpraxRQ7sRR5UJM4EWrtquuWTAIedX58n4fgNtxZqd7kquPzhAji6Ul3PMRqaqq9d+1B7BUTkyw0rzkQD7Y9DI9fejpQ8SwA0+FeJwBS+O1Nz+EUdwjAKbCs5YBNaEkm5qJSi06E0pDZz/wwZjoCc0jGX0O2Kj6XFPVRQj9AZ9ZTNteiO8uKYeU4/ykirw6eE50xgwFcAcMQcwK+iCVvEKV0scSd4JKcuczPelAjWpTkMKDKq5EkQMl50W/rhIT8FdNk9rAn1yfKRBL6H0fNSFaZOHq6OLkp2lzojz0=
    on:
      branch: master

  - provider: firebase
    project: "development"
    skip_cleanup: true
    token:
      secure: XuQO4j7xk2YJWtkXsQtIU71CXc2LjbCB3lblmsCcYlzbIWiWk1u26YxGvifpuuQ37PT2FLFnGMsWBP41kieHEw4h/AC2VkLk0cC4vhEhoMATnDDH+4RpmpdOMxMA/lWPwuNTnYMSJm2yJWV8Nz8NjdTHDSAozV2/ZXgiDKgqosXSabpoVHTH7lTcfXJAswfgdAvkeG/k4BGm1LSHTEvU+TdA9QwjmUG9PWQkkRMkEcOuH41BvY0TNMtxsAcTy0ofoDHAkhF/uOHI1J7FaEiLS1R8DwOSBY45EKEaA3dJgBqL0genpqrN7gSF8GFetF0BRXWg9mwDDdF04pgC5C1jWmtsVIjACsLQ6AChrLtpddjwwByX14i835UlFAfCP2hGGCZ5BpraxRQ7sRR5UJM4EWrtquuWTAIedX58n4fgNtxZqd7kquPzhAji6Ul3PMRqaqq9d+1B7BUTkyw0rzkQD7Y9DI9fejpQ8SwA0+FeJwBS+O1Nz+EUdwjAKbCs5YBNaEkm5qJSi06E0pDZz/wwZjoCc0jGX0O2Kj6XFPVRQj9AZ9ZTNteiO8uKYeU4/ykirw6eE50xgwFcAcMQcwK+iCVvEKV0scSd4JKcuczPelAjWpTkMKDKq5EkQMl50W/rhIT8FdNk9rAn1yfKRBL6H0fNSFaZOHq6OLkp2lzojz0=
    on:
      branch: staging

env:
  global:
    secure: XuQO4j7xk2YJWtkXsQtIU71CXc2LjbCB3lblmsCcYlzbIWiWk1u26YxGvifpuuQ37PT2FLFnGMsWBP41kieHEw4h/AC2VkLk0cC4vhEhoMATnDDH+4RpmpdOMxMA/lWPwuNTnYMSJm2yJWV8Nz8NjdTHDSAozV2/ZXgiDKgqosXSabpoVHTH7lTcfXJAswfgdAvkeG/k4BGm1LSHTEvU+TdA9QwjmUG9PWQkkRMkEcOuH41BvY0TNMtxsAcTy0ofoDHAkhF/uOHI1J7FaEiLS1R8DwOSBY45EKEaA3dJgBqL0genpqrN7gSF8GFetF0BRXWg9mwDDdF04pgC5C1jWmtsVIjACsLQ6AChrLtpddjwwByX14i835UlFAfCP2hGGCZ5BpraxRQ7sRR5UJM4EWrtquuWTAIedX58n4fgNtxZqd7kquPzhAji6Ul3PMRqaqq9d+1B7BUTkyw0rzkQD7Y9DI9fejpQ8SwA0+FeJwBS+O1Nz+EUdwjAKbCs5YBNaEkm5qJSi06E0pDZz/wwZjoCc0jGX0O2Kj6XFPVRQj9AZ9ZTNteiO8uKYeU4/ykirw6eE50xgwFcAcMQcwK+iCVvEKV0scSd4JKcuczPelAjWpTkMKDKq5EkQMl50W/rhIT8FdNk9rAn1yfKRBL6H0fNSFaZOHq6OLkp2lzojz0=
